services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/app'
        command: 'php artisan migrate:fresh --seed'
        networks:
            - dot
        depends_on:
            - database
    database:
        image: 'postgres:16'
        ports:
            - '${DB_PORT:-5432}:5432'
        env_file:
            - '.env'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db-postgres:/var/lib/postgresql/data'
        networks:
            - dot
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} -h localhost -p 5432'
                ]
            retries: 3
            timeout: 5s

networks:
    dot:
        driver: bridge
volumes:
    db-postgres:
        driver: local
